services:
  front:
    build: ./docker
    container_name: portfolio-front
    tty: true
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file: .env.local
    volumes:
      - .:/app
    command: "yarn run dev"
  
